# Generated by Django 6.0.7 on 2026-07-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
